### ISSUE TITLE
i have this issues. how to fix it?

### ISSUE THREAD

**Issue by VitalikObject** [Mimi8298/Supercell.Magic#6]
1>------ Build started: Project: Supercell.Magic.Titan, Configuration: Debug Any CPU ------
2>------ Build started: Project: Supercell.Magic.Servers.Discord, Configuration: Debug Any CPU ------
3>------ Build started: Project: Supercell.Magic.Tools.OverloadTest, Configuration: Debug Any CPU ------
1>Supercell.Magic.Titan -> E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Titan\bin\Debug\netcoreapp2.2\Supercell.Magic.Titan.dll
4>------ Build started: Project: Supercell.Magic.Logic, Configuration: Debug Any CPU ------
5>------ Build started: Project: Supercell.Magic.Tools.PatchGenerator, Configuration: Debug Any CPU ------
3>Supercell.Magic.Tools.OverloadTest -> E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Tools.OverloadTest\bin\Debug\netcoreapp2.2\Supercell.Magic.Tools.OverloadTest.dll
2>Supercell.Magic.Servers.Discord -> E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Discord\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Discord.dll
5>Supercell.Magic.Tools.PatchGenerator -> E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Tools.PatchGenerator\bin\Debug\netcoreapp2.2\Supercell.Magic.Tools.PatchGenerator.dll
4>Data\LogicNewsData.cs(153,23,153,30): warning CS0108: 'LogicNewsData.GetType()' hides inherited member 'object.GetType()'. Use the new keyword if hiding was intended.
4>Data\LogicResourceData.cs(41,52,41,67): error CS0117: 'LogicDataTables' does not contain a definition for 'GetIntegerValue'
4>Data\LogicCalendarEventFunctionData.cs(91,21,91,52): warning CS0472: The result of the expression is always 'false' since a value of type 'int' is never equal to 'null' of type 'int?'
4>Message\Alliance\War\AllianceWarMemberEntry.cs(122,17,122,24): warning CS0162: Unreachable code detected
4>Message\Alliance\War\AllianceWarMemberEntry.cs(131,17,131,24): warning CS0162: Unreachable code detected
4>Message\Alliance\War\AllianceWarMemberEntry.cs(139,17,139,24): warning CS0162: Unreachable code detected
4>Message\Alliance\War\AllianceWarMemberEntry.cs(147,17,147,24): warning CS0162: Unreachable code detected
4>Message\Alliance\AllianceFullEntryUpdateMessage.cs(72,17,72,21): warning CS0162: Unreachable code detected
4>Data\LogicProjectileData.cs(17,24,17,41): warning CS0649: Field 'LogicProjectileData.m_particleEmitter' is never assigned to, and will always have its default value null
4>Calendar\LogicOfferCalendarEvent.cs(21,21,21,28): warning CS0169: The field 'LogicOfferCalendarEvent.m_value' is never used
4>Calendar\LogicOfferCalendarEvent.cs(14,24,14,34): warning CS0169: The field 'LogicOfferCalendarEvent.m_valueTid' is never used
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(16,21,16,28): warning CS0169: The field 'AttackWarEventEntry.m_stars' is never used
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(17,21,17,44): warning CS0169: The field 'AttackWarEventEntry.m_destructionPercentage' is never used
4>Calendar\LogicOfferCalendarEvent.cs(24,22,24,42): warning CS0169: The field 'LogicOfferCalendarEvent.m_availableFrontPage' is never used
4>Data\LogicBuildingData.cs(85,21,85,41): warning CS0169: The field 'LogicBuildingData.m_targetingConeAngle' is never used
4>Mode\LogicGameMode.cs(36,21,36,40): warning CS0649: Field 'LogicGameMode.m_liveReplaySubTick' is never assigned to, and will always have its default value 0
4>Calendar\LogicOfferCalendarEvent.cs(17,24,17,47): warning CS0169: The field 'LogicOfferCalendarEvent.m_replaceBillingPackage' is never used
4>Offer\LogicOfferManager.cs(15,30,15,40): warning CS0649: Field 'LogicOfferManager.m_topOffer' is never assigned to, and will always have its default value null
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(11,27,11,39): warning CS0649: Field 'AttackWarEventEntry.m_allianceId' is never assigned to, and will always have its default value null
4>Mode\LogicGameMode.cs(26,21,26,32): warning CS0649: Field 'LogicGameMode.m_visitType' is never assigned to, and will always have its default value 0
4>Level\LogicLevel.cs(94,21,94,42): warning CS0649: Field 'LogicLevel.m_previousAttackStars' is never assigned to, and will always have its default value 0
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(8,27,8,38): warning CS0649: Field 'AttackWarEventEntry.m_accountId' is never assigned to, and will always have its default value null
4>GameObject\Component\LogicCombatComponent.cs(49,22,49,30): warning CS0649: Field 'LogicCombatComponent.m_unk504' is never assigned to, and will always have its default value false
4>GameObject\Component\LogicCombatComponent.cs(50,22,50,30): warning CS0649: Field 'LogicCombatComponent.m_unk596' is never assigned to, and will always have its default value false
4>Calendar\LogicOfferCalendarEvent.cs(19,21,19,43): warning CS0169: The field 'LogicOfferCalendarEvent.m_amountCanBePurchased' is never used
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(18,21,18,36): warning CS0649: Field 'AttackWarEventEntry.m_replayShardId' is never assigned to, and will always have its default value 0
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(9,27,9,37): warning CS0649: Field 'AttackWarEventEntry.m_avatarId' is never assigned to, and will always have its default value null
4>Calendar\LogicOfferCalendarEvent.cs(23,22,23,45): warning CS0169: The field 'LogicOfferCalendarEvent.m_availableTreasurePage' is never used
4>Level\LogicLevel.cs(111,22,111,36): warning CS0649: Field 'LogicLevel.m_ignoreAttack' is never assigned to, and will always have its default value false
4>Calendar\LogicOfferCalendarEvent.cs(10,24,10,40): warning CS0169: The field 'LogicOfferCalendarEvent.m_infoExportName' is never used
4>Calendar\LogicOfferCalendarEvent.cs(8,24,8,33): warning CS0169: The field 'LogicOfferCalendarEvent.m_infoTid' is never used
4>Calendar\LogicOfferCalendarEvent.cs(12,24,12,48): warning CS0169: The field 'LogicOfferCalendarEvent.m_shopInfoItemExportName' is never used
4>GameObject\Component\LogicHitpointComponent.cs(34,33,34,45): warning CS0169: The field 'LogicHitpointComponent.m_dieEffect2' is never used
4>Calendar\LogicOfferCalendarEvent.cs(13,24,13,41): warning CS0169: The field 'LogicOfferCalendarEvent.m_shopItemBGFrame' is never used
4>Calendar\LogicOfferCalendarEvent.cs(16,24,16,40): warning CS0169: The field 'LogicOfferCalendarEvent.m_billingPackage' is never used
4>Calendar\LogicOfferCalendarEvent.cs(7,24,7,29): warning CS0169: The field 'LogicOfferCalendarEvent.m_tid' is never used
4>GameObject\Component\LogicVillage2UnitComponent.cs(20,21,20,37): warning CS0649: Field 'LogicVillage2UnitComponent.m_productionType' is never assigned to, and will always have its default value 0
4>Calendar\LogicOfferCalendarEvent.cs(20,21,20,31): warning CS0169: The field 'LogicOfferCalendarEvent.m_priority' is never used
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(10,27,10,35): warning CS0649: Field 'AttackWarEventEntry.m_homeId' is never assigned to, and will always have its default value null
4>Calendar\LogicOfferCalendarEvent.cs(11,24,11,44): warning CS0169: The field 'LogicOfferCalendarEvent.m_shopItemExportName' is never used
4>Message\Alliance\War\Event\AttackWarEventEntry.cs(20,27,20,37): warning CS0649: Field 'AttackWarEventEntry.m_replayId' is never assigned to, and will always have its default value null
4>Calendar\LogicOfferCalendarEvent.cs(9,24,9,33): warning CS0169: The field 'LogicOfferCalendarEvent.m_infoSwf' is never used
4>Level\LogicLevel.cs(47,33,47,45): warning CS0649: Field 'LogicLevel.m_leagueData' is never assigned to, and will always have its default value null
4>Mode\LogicGameMode.cs(23,22,23,38): warning CS0649: Field 'LogicGameMode.m_liveReplayMode' is never assigned to, and will always have its default value false
4>Message\Home\GoHomeMessage.cs(14,22,14,27): warning CS0169: The field 'GoHomeMessage.m_unk' is never used
4>Data\LogicMissionData.cs(31,22,31,33): warning CS0169: The field 'LogicMissionData.m_warStates' is never used
4>GameObject\Component\LogicCombatComponent.cs(85,21,85,40): warning CS0414: The field 'LogicCombatComponent.m_damageLevelEffect' is assigned but its value is never used
4>GameObject\Component\LogicUnitProductionComponent.cs(16,22,16,28): warning CS0414: The field 'LogicUnitProductionComponent.m_mode' is assigned but its value is never used
4>GameObject\Component\LogicCombatComponent.cs(47,22,47,30): warning CS0414: The field 'LogicCombatComponent.m_unk497' is assigned but its value is never used
4>Done building project "Supercell.Magic.Logic.csproj" -- FAILED.
6>------ Build started: Project: Supercell.Magic.Servers.Core, Configuration: Debug Any CPU ------
7>------ Build started: Project: Supercell.Magic.Tools.Client, Configuration: Debug Any CPU ------
7>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
7>Done building project "Supercell.Magic.Tools.Client.csproj" -- FAILED.
6>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
6>Done building project "Supercell.Magic.Servers.Core.csproj" -- FAILED.
8>------ Build started: Project: Supercell.Magic.Servers.Proxy, Configuration: Debug Any CPU ------
9>------ Build started: Project: Supercell.Magic.Servers.Game, Configuration: Debug Any CPU ------
10>------ Build started: Project: Supercell.Magic.Servers.Home, Configuration: Debug Any CPU ------
11>------ Build started: Project: Supercell.Magic.Servers.Chat, Configuration: Debug Any CPU ------
9>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
10>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
10>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
10>Done building project "Supercell.Magic.Servers.Home.csproj" -- FAILED.
12>------ Build started: Project: Supercell.Magic.Servers.Admin, Configuration: Debug Any CPU ------
9>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
9>Done building project "Supercell.Magic.Servers.Game.csproj" -- FAILED.
11>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
11>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
11>Done building project "Supercell.Magic.Servers.Chat.csproj" -- FAILED.
13>------ Build started: Project: Supercell.Magic.Servers.Search, Configuration: Debug Any CPU ------
14>------ Build started: Project: Supercell.Magic.Servers.Stream, Configuration: Debug Any CPU ------
8>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
8>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
8>Done building project "Supercell.Magic.Servers.Proxy.csproj" -- FAILED.
13>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
13>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
13>Done building project "Supercell.Magic.Servers.Search.csproj" -- FAILED.
14>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
14>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
14>Done building project "Supercell.Magic.Servers.Stream.csproj" -- FAILED.
12>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Logic\bin\Debug\netcoreapp2.2\Supercell.Magic.Logic.dll' could not be found
12>CSC : error CS0006: Metadata file 'E:\Downloads\Supercell.Magic-patch-2\Supercell.Magic-patch-2\Supercell.Magic.Servers.Core\bin\Debug\netcoreapp2.2\Supercell.Magic.Servers.Core.dll' could not be found
12>Done building project "Supercell.Magic.Servers.Admin.csproj" -- FAILED.
========== Build: 4 succeeded, 10 failed, 0 up-to-date, 0 skipped ==========

**Comment by lucifer-psycho** [comment]
Refer to issue [#4](https://github.com/Mimi8298/Supercell.Magic/issues/4) for information on database.
